Make test helpers robust to running with errexit (set -e)
If the helpers ran commands that (expectedly) failed, they could take down whole
tests running with set -e. They now preserve the errexit bit and turn it off
around their own functionality.

diff --git a/Scripts/test-helpers b/Scripts/test-helpers
--- a/Scripts/test-helpers
+++ b/Scripts/test-helpers
@@ -1,9 +1,12 @@
 # Basic helpers sourced by some of the tests.
 
+# A subset of the tests uses "set -e", so we need to ensure that helpers that
+# may naturally hit transient failures don't abort a test. We temporarily set +e
+# in such functions.
+
 # Exits with error and error message.
 fail() {
     local msg="$1"
-
     echo "failure: $msg"
     exit 1
 }
@@ -15,14 +18,23 @@ run() {
     local ret="$2"
     local name="$3"
 
-    # Save outputs if caller requested it
-    if [ -n "$name" ]; then
-        { eval "$cmd"; } >output.$name 2>stderr.$name
-    else
-        eval "$cmd"
-    fi
+    _impl() {
+        # Save outputs if caller requested it
+        if [ -n "$name" ]; then
+            { eval "$cmd"; } >output.$name 2>stderr.$name
+        else
+            eval "$cmd"
+        fi
+        [ $? -eq $ret ] || fail "[$name] '$cmd' did not exit with $ret"
+    }
 
-    [ $? -eq $ret ] || fail "[$name] '$cmd' did not exit with $ret"
+    local errexit=false
+    [ -o errexit ] && errexit=true
+    set +e
+    _impl
+    [ $errexit == true ] && set -e
+
+    return 0
 }
 
 # Try a given command repeatedly for up to 5 seconds until it succeeds.
@@ -46,32 +58,58 @@ try_until() {
 wait_for_instances() {
     local num_instances="$1"
 
-    for i in $(seq 10); do
-        [ $(zeek_client get-instances | jq 'keys|length') -eq $num_instances ] && return 0
-        sleep 1
-    done
+    _impl() {
+        for i in $(seq 10); do
+            local cur_instances=$(zeek_client get-instances | jq 'keys|length')
+            if [ -n "$cur_instances" ] && [ $cur_instances -eq $num_instances ]; then
+                return 0
+            fi
+            sleep 1
+        done
 
-    return 1
+        return 1
+    }
+
+    local errexit=false
+    [ -o errexit ] && errexit=true
+    set +e
+    _impl
+    local ret=$?
+    [ $errexit == true ] && set -e
+
+    return $ret
 }
 
 # Checks current cluster node state via "zeek-client get-nodes" until nodes get
 # reported and all nodes are in running state, or 10 seconds have passed. Exits
 # with 0 once all nodes are running, 1 when the timeout is hit or other problems
-# arise.
+# arise. Takes one optional argument: the number of nodes to expect.
 wait_for_all_nodes_running() {
-    for i in $(seq 10); do
-        # Retrieve node status, and extract run states from it.
-        # Count how often that is "RUNNING" vs something else.
-        zeek_client get-nodes \
-            | jq -r '.results[][].state' \
-            | awk "/RUNNING/  { r += 1 }
+    local nodes=${1:-0}
+
+    _impl() {
+        for i in $(seq 10); do
+            # Retrieve node status, and extract run states from it.
+            # Count how often that is "RUNNING" vs something else.
+            zeek_client get-nodes \
+                | jq -r '.results[][].state' \
+                | awk "/RUNNING/  { r += 1 }
                    !/RUNNING/ { o += 1 }
-                   END        { if ( r > 0 && o == 0 ) { exit 0 };
+                   END        { if ( r > 0 && o == 0 && ( $nodes == 0 || $nodes == r ) ) { exit 0 };
                                 exit 1 }"
 
-        [ $? -eq 0 ] && return 0
-        sleep 1
-    done
+            [ $? -eq 0 ] && return 0
+            sleep 1
+        done
 
-    return 1
+        return 1
+    }
+
+    local errexit=false
+    [ -o errexit ] && errexit=true
+    set +e
+    _impl
+    local ret=$?
+    [ $errexit == true ] && set -e
+    return $ret
 }
